---

version: 2
jobs:
  build:
    working_directory: ~/timesheet

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - restore_cache:
          key: timesheet-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: timesheet-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/timesheet-1.0-SNAPSHOT.jar